spring:
    profiles:
        include: API-KEY
    #mysql
    datasource:
        url: jdbc:mysql://localhost:3306/ssafyromeda?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: ssafy
        password: ${mysql-password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    #security, oauth2
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${kakao-client-id}
                        client-secret: ${kakao-client-secret}
                        scope:
                            -email
                        redirect-uri: "localhost:8080/login/oauth2/code/kakao"
                        authorization-grant-type: authorization_code
                        client-name: kakao
                        client-authentication-method: POST

                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
    #jpa sql
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    # redis
    redis:
        host: 127.0.0.1
        port: 6379

# jwt
springboot:
  jwt:
    secret: "asamfeoyrsd"




