jwt:
  #base64로 인코딩된 암호 키, HS512를 사용할 것이기 때문에, 512비트(64바이트) 이상이 되어야 합니다.
  secretKey: s08-webmobile1-sub2-S08P12D205-96s-SSAFYROMEDA-rndbrwm-ttkvlfhapek

  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 1209600000 #  2주
    header: RefreshToken