spring:
    profiles:
        include:
            - KEY
            - JWT
            - OAUTH
    #mysql
    datasource:
        url: jdbc:mysql://i8d205.p.ssafy.io:3306/ssafyromeda?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul #13.125.29.108
        username: root #d205
        password: ${mysql-password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    #jpa sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update # 스키마 자동 생성
        database: mysql

    redis:
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        port: 6379
        host: i8d205.p.ssafy.io
        password: ${redis-password}


## jwt
#springboot:
#  jwt:
#    secret: "asamfeoyrsd"

# openvidu
openvidu:
    url: https://localhost:4443
    secret: MY_SECRET

server:
    ssl:
        enabled: false
    port: 8080
    servlet:
        context-path: /api