spring:
#mysql ??
    datasource:
        url: jdbc:mysql://localhost:3306/ssafyromeda?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: ssafy
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

#jpa sql ??
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

# redis
    redis:
        host: 127.0.0.1
        port: 6379

# jwt
springboot:
  jwt:
    secret: "asamfeoyrsd"


