spring:
    profiles:
        include: KEY
    #mysql
    datasource:
        url: jdbc:mysql://localhost:3306/ssafyromeda?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: ssafy
        password: ${mysql-password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    #jpa sql
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql

    # redis
    redis:
        host: 127.0.0.1
        port: 6379

# jwt
springboot:
  jwt:
    secret: "asamfeoyrsd"

# openvidu
openvidu:
    url: https://localhost:4443/
    secret: MY_SECRET




